# Generated by Django 5.2.16 on 2026-07-16 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ppt_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementAnimation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_selector', models.CharField(max_length=255, verbose_name='元素选择器')),
                ('animation_type', models.CharField(choices=[('entrance', '入场'), ('emphasis', '强调'), ('exit', '退出')], max_length=10, verbose_name='动画类型')),
                ('effect', models.CharField(choices=[('fadeIn', '淡入'), ('fadeInUp', '上移入'), ('fadeInDown', '下移入'), ('fadeInLeft', '左移入'), ('fadeInRight', '右移入'), ('zoomIn', '放大'), ('zoomOut', '缩小'), ('bounceIn', '弹入'), ('slideInUp', '上滑入'), ('slideInDown', '下滑入'), ('slideInLeft', '左滑入'), ('slideInRight', '右滑入'), ('rotateIn', '旋转入'), ('flipInX', 'X轴翻转'), ('flipInY', 'Y轴翻转')], default='fadeIn', max_length=20, verbose_name='效果')),
                ('trigger', models.CharField(choices=[('auto', '自动'), ('click', '点击'), ('sequential', '顺序')], default='auto', max_length=10, verbose_name='触发方式')),
                ('duration', models.IntegerField(default=600, verbose_name='时长(ms)')),
                ('delay', models.IntegerField(default=0, verbose_name='延迟(ms)')),
                ('order', models.IntegerField(default=0, verbose_name='顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animations', to='ppt_sessions.sessionpage', verbose_name='页面')),
            ],
            options={
                'verbose_name': '元素动画',
                'verbose_name_plural': '元素动画',
                'db_table': 'element_animations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_selector', models.CharField(blank=True, max_length=255, verbose_name='元素选择器')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('before_state', models.JSONField(blank=True, default=dict, verbose_name='编辑前状态')),
                ('after_state', models.JSONField(blank=True, default=dict, verbose_name='编辑后状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_edits', to='ppt_sessions.sessionoperation', verbose_name='操作')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='ppt_sessions.sessionpage', verbose_name='页面')),
            ],
            options={
                'verbose_name': '页面编辑',
                'verbose_name_plural': '页面编辑',
                'db_table': 'page_edits',
                'ordering': ['created_at'],
            },
        ),
    ]
