# Generated by Django 5.2.16 on 2026-07-16 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ppt_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='设置键')),
                ('value', models.TextField(verbose_name='设置值')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '应用设置',
                'verbose_name_plural': '应用设置',
                'db_table': 'app_settings',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='偏好键')),
                ('value', models.TextField(verbose_name='偏好值')),
                ('confidence', models.FloatField(default=1.0, verbose_name='置信度')),
                ('source_sessions', models.JSONField(blank=True, default=list, verbose_name='来源会话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
            ],
            options={
                'verbose_name': '用户偏好',
                'verbose_name_plural': '用户偏好',
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='ModelUsageEvent',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50, verbose_name='提供商')),
                ('model', models.CharField(max_length=100, verbose_name='模型')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='输入Token')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='输出Token')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token')),
                ('usage_source', models.CharField(default='provider', max_length=20, verbose_name='用量来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppt_sessions.modelconfig', verbose_name='模型配置')),
            ],
            options={
                'verbose_name': '模型使用记录',
                'verbose_name_plural': '模型使用记录',
                'db_table': 'model_usage_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='idx_model_usage_created'), models.Index(fields=['provider', 'model', 'created_at'], name='idx_model_usage_model')],
            },
        ),
    ]
