# Generated by Django 5.2.16 on 2026-07-16 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ppt_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('png-long', 'PNG长图'), ('pptx', 'PPTX'), ('mp4', 'MP4'), ('html', 'HTML打包')], max_length=10, verbose_name='导出格式')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=10, verbose_name='状态')),
                ('output_path', models.CharField(blank=True, max_length=500, verbose_name='输出路径')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('error', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='ppt_sessions.session', verbose_name='会话')),
            ],
            options={
                'verbose_name': '导出任务',
                'verbose_name_plural': '导出任务',
                'db_table': 'export_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
