# Generated by Django 5.2.16 on 2026-07-16 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ppt_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='提供商名称')),
                ('provider_type', models.CharField(max_length=50, verbose_name='类型')),
                ('base_url', models.CharField(max_length=255, verbose_name='API地址')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI提供商',
                'verbose_name_plural': 'AI提供商',
                'db_table': 'ai_providers',
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=50, verbose_name='任务类型')),
                ('messages', models.JSONField(default=list, verbose_name='消息列表')),
                ('status', models.CharField(choices=[('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='running', max_length=10, verbose_name='状态')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='结果')),
                ('error', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='ppt_sessions.session', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'AI对话',
                'verbose_name_plural': 'AI对话',
                'db_table': 'ai_conversations',
                'ordering': ['-created_at'],
            },
        ),
    ]
