# Generated by Django 5.2.16 on 2026-07-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIProvider',
        ),
    ]
